CREATE DATABASE BD_CLINICA2;

USE BD_CLINICA2;

CREATE TABLE USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    CPF_USUARIO VARCHAR(11),
    NOME_USUARIO VARCHAR(45),
    SENHA_USUARIO VARCHAR(45)
);

SELECT * FROM USUARIOS;

INSERT INTO USUARIOS (CPF_USUARIO, NOME_USUARIO, SENHA_USUARIO) 
	VALUES (12345678910, 'admin', 'admin');

CREATE TABLE MEDICOS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
    NOME VARCHAR(45) NOT NULL,
    IDADE INT NOT NULL,
    ESPECIALIDADE VARCHAR(45) NOT NULL,
    SALA INT NOT NULL UNIQUE,
	TURNO VARCHAR(10) NOT NULL,
    VALOR FLOAT NOT NULL
);

SELECT * FROM MEDICOS;

INSERT INTO MEDICOS
    (NOME, IDADE, ESPECIALIDADE, SALA, TURNO, VALOR)
    VALUES ("PRISCILA", 29, "DERMATOLOGISTA", 31, "MANHA", 150),
           ("CARLOS", 33, "PEDIATRA", 2, "TARDE", 200),
           ("ROBERTA", 26, "ORTOPEDISTA", 3, "MANHA", 250),
           ("MANUEL", 27, "CARDIOLOGISTA", 25, "MANHA", 180);
           
SELECT * FROM MEDICOS;

